# Generated by Django 2.0.2 on 2018-03-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(to='shop.Provider'),
        ),
    ]
